name: dial-in CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  lint: # TODO: rename after implementing tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install node
        uses: actions/setup-node@v6

      - run: |
          npm install

      - name: Lint
        run: just lint

      # - name: Test
      #   run: just test

  # TODO: need nerdctl on runner to utilize existing build script..
  # build:
  #   runs-on: ubuntu-latest
  #   needs: lint-and-test
  #   # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v6

  #     - name: Install just
  #       uses: extractions/setup-just@v3

  #     - name: Log in to GitHub Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     # Can't use this recipe without install nerdctl first; no plugin exists yet
  #     - name: Build image
  #       run: just build

  #     - name: Tag and push image
  #       run: |
  #         docker tag $(just get-image-name) ${{ env.IMAGE_NAME }}
  #         docker push ${{ env.IMAGE_NAME }}
  #         docker tag ${{ env.IMAGE_NAME }} ghcr.io/${{ github.repository }}:latest
  #         docker push ghcr.io/${{ github.repository }}:latest

  # TODO: Set up deployment credentials in repo secrets
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Deploy to host
  #       uses: appleboy/ssh-action@v1
  #       with:
  #         host: ${{ secrets.DEPLOY_HOST }}
  #         username: ${{ secrets.DEPLOY_USER }}
  #         key: ${{ secrets.DEPLOY_SSH_KEY }}
  #         script: |
  #           # Pull the new image
  #           echo "${{ secrets.GITHUB_TOKEN }}" | nerdctl login ghcr.io -u ${{ github.actor }} --password-stdin
  #           nerdctl pull ${{ env.IMAGE_NAME }}
  #           nerdctl tag ${{ env.IMAGE_NAME }} dial-in:latest


  #           # Navigate to compose directory
  #           cd /path/to/your/compose/stack

  #           # Recreate the service
  #           nerdctl compose down your-service
  #           nerdctl compose up -d your-service

  #           # Clean up old images (optional)
  #           nerdctl image prune -f
